blank_issues_enabled: false

contact_links:
  - name: Ask a question on how to use XenForo Coding Standards Fixer
    url: https://xenforo.com/community/forums/xenforo-development-discussions.34/
    about: For general-purpose questions and answers, see our development discussions forum.
