name: Composer

on:
  workflow_dispatch:

  push:
    branches:
      - "main"
    paths:
      - "composer.json"
      - "composer.lock"

  pull_request:
    branches:
      - "main"
    paths:
      - "composer.json"
      - "composer.lock"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  composer:
    name: Composer
    runs-on: ubuntu-latest
    container: ghcr.io/xenforo-ltd/php-ci:8.5
    permissions:
      contents: read
      packages: read # required for php-ci container

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Composer
        run: composer validate
