name: PHPStan

on:
  workflow_dispatch:
    inputs:
      exclude_baseline:
        description: 'Exclude baseline'
        type: boolean
        default: false

  push:
    branches:
      - 'main'
    paths:
      - '**.php'

  pull_request:
    branches:
      - 'main'
    paths:
      - '**.php'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    container: ghcr.io/xenforo-ltd/php-ci:8.2

    steps:
      - name: Install git
        run: apk add --no-cache git

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get cache data
        id: cache-data
        run: |
          echo "composer_path=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Set up Composer cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.cache-data.outputs.composer_path }}
          key: composer-${{ steps.cache-data.outputs.date }}
          restore-keys: composer-

      - name: Install dependencies
        run: composer install

      - name: Set up PHPStan cache
        uses: actions/cache@v4
        with:
          path: /tmp/phpstan
          key: phpstan-${{ steps.cache-data.outputs.date }}
          restore-keys: |
            phpstan-${{ steps.cache-data.outputs.date }}
            phpstan-

      - name: PHPStan
        run: composer ${{ inputs.exclude_baseline && 'phpstan:all' || 'phpstan' }}
